<?php

return [
    'patient_records' => [
        'id_exact' => 240,
        'patient_name_exact' => 200,
        'patient_name_prefix' => 140,
        'patient_name_contains' => 90,
        'patient_name_token' => 35,
        'barangay_exact' => 110,
        'barangay_prefix' => 75,
        'barangay_contains' => 45,
        'branch_exact' => 85,
        'branch_prefix' => 55,
        'branch_contains' => 30,
        'purok_exact' => 70,
        'purok_prefix' => 45,
        'purok_contains' => 25,
        'category_exact' => 30,
    ],
    'history_logs' => [
        'action_exact' => 180,
        'action_prefix' => 120,
        'action_contains' => 70,
        'user_exact' => 140,
        'user_prefix' => 90,
        'user_contains' => 50,
        'description_prefix' => 60,
        'description_contains' => 30,
        'description_token' => 15,
        'date_exact' => 40,
    ],
    'product_movements' => [
        'batch_exact' => 190,
        'batch_prefix' => 130,
        'batch_contains' => 80,
        'product_exact' => 160,
        'product_prefix' => 110,
        'product_contains' => 65,
        'description_prefix' => 90,
        'description_contains' => 50,
        'description_token' => 20,
        'user_exact' => 70,
        'branch_exact' => 70,
        'type_exact' => 45,
    ],
    'inventory' => [
        'batch_exact' => 190,
        'batch_prefix' => 130,
        'batch_contains' => 80,
        'generic_exact' => 160,
        'generic_prefix' => 110,
        'generic_contains' => 65,
        'generic_token' => 20,
        'brand_exact' => 110,
        'brand_prefix' => 75,
        'brand_contains' => 45,
        'form_exact' => 30,
        'strength_exact' => 30,
    ],
];
